### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by AdityaKane2001** [ankit-vaidya19/cv_models#2]
@ankit-vaidya19 

Add a README file which outlines the contents of the repo and its usage.

**Comment by ankit-vaidya19** [comment]
@AdityaKane2001 solved

**Comment by AdityaKane2001** [comment]
Provide links to files in readme

**Comment by ankit-vaidya19** [comment]
@AdityaKane2001 provided link to papers

**Comment by AdityaKane2001** [comment]
Not just the papers, but the code files as well. Better yet to make a table.

Also the README has many small grammatical errors. Please fix them.

**Comment by AdityaKane2001** [comment]
The general convention for the README file is to keep its name `README` itself, and not the lowercase version.

**Comment by ankit-vaidya19** [comment]
Any more changes?

**Comment by AdityaKane2001** [comment]
Yeah, the link is `https://github.com/ankit-vaidya19/cv_models/blob/e5183aee0336c8efa1adfbff980f192462d46fe8/models/AlexNet.py`

change the commit hash to `main` so that the visitors will always be able to access the latest version and not an older one:

`https://github.com/ankit-vaidya19/cv_models/blob/main/models/AlexNet.py`

**Comment by ankit-vaidya19** [comment]
done
