### ISSUE TITLE
Use the variables in dataset.py in all model files

### ISSUE THREAD

**Issue by AdityaKane2001** [ankit-vaidya19/cv_models#4]
You have created the data variables in dataset.py. Use the same in all model files. There is no point in making a data file if the data is not going to be used. 

Also preferably write a class with proper methods. Then instantiate and use this class in the model files.

**Comment by ankit-vaidya19** [comment]
is the data class okay?
I will make further changes or improvements during the weekend due to submission crunch. If that is okay

**Comment by AdityaKane2001** [comment]
> I will make further changes or improvements during the weekend due to submission crunch. If that is okay

Sure.

Don't directly commit to the main branch, make a separate branch for each major change and open a pull request. That way, I can review stuff easily and you can better keep track of the changes.
